### ISSUE TITLE
I have a problem of the dataset.

### ISSUE THREAD

**Issue by zhaoyihao12345** [EmmaW8/pOSAL#2]
I found that not all of the OD regions are covered by the cropped ROI in Drishti-GS dataset provided by you. Why?

**Comment by emma-sjwang** [comment]
Could you provide more information?
Actually, In my previous experiments, the OD regions can successfully be covered!
If not, you can adjust the radius to make it be covered.

**Comment by zhaoyihao12345** [comment]
I am very glad to hear from you. The OD regions are not completely covered by the cropped ROI, for example,  the images named 'gdrishtiGS_032.png' and 'gdrishtiGS_005.png' in Drishti-GS dataset provided by you.

**Comment by emma-sjwang** [comment]
I am sorry that I did not find the 'gdrishtiGS_032.png' in the results link that I provided.
For the figure 'gdrishtiGS_005.png', it is well segmented which means the ROI is cropped correctly.
Please download the results from the project website https://emmaw8.github.io/pOSAL/index.html.

**Comment by zhaoyihao12345** [comment]
The two images are 'data/Drishti-GS/train/disc_small/image/gdrishtiGS_032.png' and&nbsp;'data/Drishti-GS/train/disc_small/image/gdrishtiGS_032.png'. I can find them in your github.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shujun WANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午4:40
收件人:&nbsp;"EmmaW8/pOSAL"<pOSAL@noreply.github.com&gt;;
抄送:&nbsp;"1152048717"<1152048717@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EmmaW8/pOSAL] I have a problem of the dataset. (#2)




I am sorry that I did not find the 'gdrishtiGS_032.png' in the results link that I provided.
 For the figure 'gdrishtiGS_005.png', it is well segmented which means the ROI is cropped correctly.
 Please download the results from the project website https://emmaw8.github.io/pOSAL/index.html.

**Comment by zhaoyihao12345** [comment]
The two images are 'data/Drishti-GS/train/disc_small/image/gdrishtiGS_032.png' and 'data/Drishti-GS/test/disc_small/image/gdrishtiGS_005.png'. I can find them in your github.







------------------ 原始邮件 ------------------
发件人:&nbsp;"Shujun WANG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午4:40
收件人:&nbsp;"EmmaW8/pOSAL"<pOSAL@noreply.github.com&gt;;
抄送:&nbsp;"1152048717"<1152048717@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EmmaW8/pOSAL] I have a problem of the dataset. (#2)




I am sorry that I did not find the 'gdrishtiGS_032.png' in the results link that I provided.
 For the figure 'gdrishtiGS_005.png', it is well segmented which means the ROI is cropped correctly.
 Please download the results from the project website https://emmaw8.github.io/pOSAL/index.html.

**Comment by emma-sjwang** [comment]
If you cannot accept it, you can change the cover range to cover the ROI. I uploaded an optional training set named 'disc_small' for your reference you can design your own dataset according to a reasonable range.
In my experiment, I may use the ROIs saved in 'disc' but I did not release it.
For the test ROI, actually it didn't matter since we directly predict the results from the whole image, the cropped ROI was used for evaluation during the training.
Hope this can help you.

**Comment by zhaoyihao12345** [comment]
Thank you very much.
