### ISSUE TITLE
evaluate_segmentation_results missing

### ISSUE THREAD

**Issue by xavieryxie** [EmmaW8/pOSAL#3]
Thanks for your great work, but when i am testing the model,  the evaluate_segmentation_results function is missing. Could you upload it at you convenience? Thank you very much.

**Comment by xavieryxie** [comment]
Oh, another problem, is the function in utils.py (save_img and save_per_img) are same? save_per_img is also missing.

**Comment by emma-sjwang** [comment]
Hi,
Thank you for your interest in our work.
But now, I don't have time to maintain the code.
For the evaluate_segmentation_results function, please refer to https://github.com/ignaciorlando/refuge-evaluation/blob/b8fc1a8bd1bdd3eddd63bad8775ccfa4258488bb/evaluation_metrics/evaluation_metrics_for_segmentation.py#L213

Our function is inherited from their evaluation codes.
And for the 'save_img and save_per_img', please feel free to update it by yourself.

Hope this could help you.

**Comment by emma-sjwang** [comment]
Please refer #5 for more details. #
